EventHubApp/Controllers/EventController.cs
using EventHubApp.Services.Core.Interfaces;
using EventHubApp.Web.ViewModels.Event;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

using static EventHubApp.Web.ViewModels.ValidationMessages.Event;

namespace EventHubApp.Web.Controllers
{
    public class EventController : BaseController
    {
        private readonly IEventService eventService;
        private readonly IWatchlistService watchlistService;

        
        public EventController(IEventService eventService, IWatchlistService watchlistService)
        {
            this.eventService = eventService;
            this.watchlistService = watchlistService;
        }

        [HttpGet]
        [AllowAnonymous]
        public async Task<IActionResult> Index()
        {
            IEnumerable<AllEventsIndexViewModel> allEvents = await this.eventService
                .GetAllEventsAsync();
            if (this.IsUserAuthenticated())
            {
                foreach (AllEventsIndexViewModel eventIndexVM in allEvents)
                {
                    eventIndexVM.IsAddedToUserWatchlist = await this.watchlistService
                        .IsEventAddedToWatchlist(eventIndexVM.Id, this.GetUserId());
                }
            }

            return View(allEvents);
        }

        [HttpGet]
        public async Task<IActionResult> Add()
        {
            return this.View();
        }

        [HttpPost]
        public async Task<IActionResult> Add(EventFormInputModel inputModel)
        {
            if (!this.ModelState.IsValid)
            {
                return this.View(inputModel);
            }

            try
            {
                await this.eventService.AddEventAsync(inputModel);

                return this.RedirectToAction(nameof(Index));
            }
            catch (Exception e)
            {

                Console.WriteLine(e.Message);

                this.ModelState.AddModelError(string.Empty, ServiceCreateError);
                return this.View(inputModel);
            }
        }



        [HttpGet]
        [AllowAnonymous]
        public async Task<IActionResult> Details(string? id)
        {
            try
            {
                EventDetailsViewModel? eventDetails = await this.eventService
                    .GetEventDetailsByIdAsync(id);
                if (eventDetails == null)
                {

                    return this.RedirectToAction(nameof(Index));
                }

                return this.View(eventDetails);
            }
            catch (Exception e)
            {

                Console.WriteLine(e.Message);

                return this.RedirectToAction(nameof(Index));
            }
        }

        [HttpGet]
        [AllowAnonymous]
        public async Task<IActionResult> DetailsPartial(string? id)
        {
            try
            {
                EventDetailsViewModel? eventDetails = await this.eventService
                    .GetEventDetailsByIdAsync(id);
                if (eventDetails == null)
                {

                    return this.RedirectToAction(nameof(Index));
                }

                return this.View("_EventDetailsPartial", eventDetails);
            }
            catch (Exception e)
            {

                Console.WriteLine(e.Message);

                return this.RedirectToAction(nameof(Index));
            }
        }

        [HttpGet]
        public async Task<IActionResult> Edit(string? id)
        {
            try
            {
                EventFormInputModel? editableEvent = await this.eventService
                    .GetEditableEventByIdAsync(id);
                if (editableEvent == null)
                {

                    return this.RedirectToAction(nameof(Index));
                }

                return this.View(editableEvent);
            }
            catch (Exception e)
            {

                Console.WriteLine(e.Message);

                return this.RedirectToAction(nameof(Index));
            }
        }

        [HttpPost]
        public async Task<IActionResult> Edit(EventFormInputModel inputModel)
        {
            if (!this.ModelState.IsValid)
            {
                return this.View(inputModel);
            }

            try
            {
                bool editSuccess = await this.eventService.EditEventAsync(inputModel);
                if (!editSuccess)
                {

                    return this.RedirectToAction(nameof(Index));
                }

                return this.RedirectToAction(nameof(Details), new { id = inputModel.Id });
            }
            catch (Exception e)
            {

                Console.WriteLine(e.Message);

                return this.RedirectToAction(nameof(Index));
            }
        }

        [HttpGet]
        public async Task<IActionResult> Delete(string? id)
        {
            try
            {
                DeleteEventViewModel? eventToBeDeleted = await this.eventService
                    .GetEventDeleteDetailsByIdAsync(id);
                if (eventToBeDeleted == null)
                {

                    return this.RedirectToAction(nameof(Index));
                }

                return this.View(eventToBeDeleted);
            }
            catch (Exception e)
            {

                Console.WriteLine(e.Message);

                return this.RedirectToAction(nameof(Index));
            }
        }

        [HttpPost]
        public async Task<IActionResult> Delete(DeleteEventViewModel inputModel)
        {
            try
            {
                if (!this.ModelState.IsValid)
                {
                    return this.RedirectToAction(nameof(Index));
                }

                bool deleteResult = await this.eventService
                    .SoftDeleteEventAsync(inputModel.Id);
                if (deleteResult == false)
                {

                    return this.RedirectToAction(nameof(Index));
                }


                return this.RedirectToAction(nameof(Index));
            }
            catch (Exception e)
            {

                Console.WriteLine(e.Message);

                return this.RedirectToAction(nameof(Index));
            }
        }







    }
}

EventHubApp/Controllers/PlaceController.cs
using EventHubApp.Services.Core.Interfaces;
using EventHubApp.Web.ViewModels.Place;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace EventHubApp.Web.Controllers
{
    public class PlaceController : BaseController
    {
        private readonly IPlaceService placeService;

        public PlaceController(IPlaceService placeService)
        {
            this.placeService = placeService;
        }

        [HttpGet]
        [AllowAnonymous]
        public async Task<IActionResult> Index()
        {
            try
            {
                IEnumerable<UsersPlaceIndexViewModel> allPlacesUserView = await this.placeService
                    .GetAllPlacesUserViewAsync();

                return View(allPlacesUserView);
            }
            catch (Exception e)
            {
                Console.WriteLine(e);

                return this.RedirectToAction(nameof(Index), "Home");
            }
        }

        [HttpGet]
        [AllowAnonymous]
        public async Task<IActionResult> Program(string? id)
        {
            try
            {
                // TODO: Implement showing Showtimes on Program and choosing Showtime when buying a Ticket
                PlaceProgramViewModel? placeProgram = await this.placeService
                    .GetPlaceProgramAsync(id);
                if (placeProgram == null)
                {
                    return this.RedirectToAction(nameof(Index));
                }

                return this.View(placeProgram);
            }
            catch (Exception e)
            {
                Console.WriteLine(e);

                return this.RedirectToAction(nameof(Index));
            }
        }

        [HttpGet]
        [AllowAnonymous]
        public async Task<IActionResult> Details(string? id)
        {
            try
            {
                PlaceDetailsViewModel? placeProgram = await this.placeService
                    .GetPlaceDetailsAsync(id);
                if (placeProgram == null)
                {
                    return this.RedirectToAction(nameof(Index));
                }

                return this.View(placeProgram);
            }
            catch (Exception e)
            {
                Console.WriteLine(e);

                return this.RedirectToAction(nameof(Index));
            }
        }
    }

}

EventHubApp/Controllers/TicketController.cs
using EventHubApp.Services.Core.Interfaces;
using EventHubApp.Web.ViewModels.Ticket;
using Microsoft.AspNetCore.Mvc;

namespace EventHubApp.Web.Controllers
{
    public class TicketController : BaseController
    {
        private readonly ITicketService ticketService;

        public TicketController(ITicketService ticketService)
        {
            this.ticketService = ticketService;
        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            string? userId = this.GetUserId();

            IEnumerable<TicketIndexViewModel> allTickets = await this.ticketService
                .GetUserTicketsAsync(userId);

            return View(allTickets);
        }
    }
}

EventHubApp/Controllers/WatchlistController.cs
using EventHubApp.Services.Core.Interfaces;
using EventHubApp.Web.ViewModels.Watchlist;
using Microsoft.AspNetCore.Mvc;

namespace EventHubApp.Web.Controllers
{
    public class WatchlistController : BaseController
    {
        private readonly IWatchlistService watchlistService;

        public WatchlistController(IWatchlistService watchlistService)
        {
            this.watchlistService = watchlistService;
        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            try
            {
                string? userId = this.GetUserId();
                if (userId == null)
                {
                    return this.Forbid();
                }

                IEnumerable<WatchlistViewModel> userWatchlist = await this.watchlistService
                    .GetUserWatchlistAsync(userId);
                return View(userWatchlist);
            }
            catch (Exception e)
            {
                Console.WriteLine(e.Message);

                return this.RedirectToAction(nameof(Index), "Home");
            }
        }


        [HttpPost]
        public async Task<IActionResult> Add(string? eventId)
        {
            try
            {
                string? userId = this.GetUserId();
                if (userId == null)
                {
                    return this.Forbid();
                }

                bool result = await this.watchlistService
                    .AddEventToUserWatchlistAsync(eventId, userId);
                if (result == false)
                {
                    return this.RedirectToAction(nameof(Index), "Event");
                }

                return this.RedirectToAction(nameof(Index));
            }
            catch (Exception e)
            {
                Console.WriteLine(e.Message);

                return this.RedirectToAction(nameof(Index), "Home");
            }
        }

        [HttpPost]
        public async Task<IActionResult> Remove(string? eventId)
        {
            try
            {
                string? userId = this.GetUserId();
                if (userId == null)
                {
                    return this.Forbid();
                }

                bool result = await this.watchlistService
                    .RemoveEventFromWatchlistAsync(eventId, userId);
                if (result == false)
                {
                    return this.RedirectToAction(nameof(Index));
                }

                return this.RedirectToAction(nameof(Index), "Event");
            }
            catch (Exception e)
            {
                Console.WriteLine(e.Message);

                return this.RedirectToAction(nameof(Index), "Home");
            }
        }




    }
}

EventHubApp/Views/Shared/_BuyTicketModalPartial.cshtml
<div class="modal fade" id="buyTicketModal" tabindex="-1" aria-labelledby="buyTicketModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header bg-dark text-white">
                <h5 class="modal-title" id="buyTicketModalLabel">
                    Buy Ticket - <span id="placeNamePlaceholder"></span>
                </h5>
                <button type="button" class="btn-close btn-close-white" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>

            <div class="modal-body bg-light text-dark">
                <input type="hidden" id="placeId">
                <input type="hidden" id="eventId">

                <div id="availableTicketsDiv" class="mb-3" hidden>
                    <label class="form-label fw-bold text-dark">Available Tickets:</label>
                    <p id="availableTicketsCount" class="text-success fw-bold mb-0">Loading...</p>
                </div>

                <label for="showtimeSelect" class="form-label fw-bold text-dark">Select Showtime:</label>
                <select id="showtimeSelect" class="form-select border-dark">
                    <option value="" disabled selected>Choose a time</option>
                    <option value="2025-07-16T19:00">15:00</option>
                    <option value="2025-07-16T21:30">21:30</option>
                </select>

                <label for="quantity" class="form-label fw-bold text-dark">Number of Tickets:</label>
                <input type="number" id="quantity" class="form-control border-dark" min="1" value="1">

                <p id="errorMessage" class="text-danger d-none mt-2 fw-bold"></p>
            </div>

            <div class="modal-footer bg-white">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
                <button type="button" id="buyTicketButton" class="btn btn-success fw-bold">Confirm Purchase</button>
            </div>
        </div>
    </div>
</div>

EventHubApp/Views/Shared/_EventDetailsPartial.cshtml
@using EventHubApp.Web.ViewModels.Event;
@model EventDetailsViewModel;

@{
    Layout = null;
}

<div class="container-fluid">
    <div class="row">
        <div class="col-md-4">
            <img src="@Model.ImageUrl"
                 class="img-fluid rounded shadow"
                 alt="@Model.Title">
        </div>
        <div class="col-md-8">
            <h3 class="fw-bold">@Model.Title</h3>
            <p><strong>Type:</strong> @Model.Type</p>
            <p><strong>Release Date:</strong> @Model.ReleaseDate</p>
            <p><strong>Sponsor:</strong> @Model.Sponsor</p>
            <p><strong>Duration:</strong> @Model.Duration days</p>
            <p class="mt-3">@Model.Description</p>
        </div>
    </div>
</div>

EventHubApp/Views/Shared/_Layout.cshtml
﻿@{
	int currentYear = DateTime.UtcNow.Year;
	string footerNote = (2025 == currentYear) ? $"{currentYear}" : $"{2025} - {currentYear}";
}


<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - EventHubApp</title>
    @* <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" /> *@
    <link rel="stylesheet" href="~/css/style.css"/>
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/EventHubApp.styles.css" asp-append-version="true" />

    @await RenderSectionAsync("Styles", false)
</head>
<body>
    <header>

        <nav class="navbar navbar-expand-lg bg-primary" data-bs-theme="dark">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">EventHub</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarColor01">
                    <ul class="navbar-nav me-auto">
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Place" asp-action="Index">Places</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Event" asp-action="Index">Events</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#">About</a>
                        </li>

                        @if (User?.Identity?.IsAuthenticated ?? false)
						{

                            <li class="nav-item">
                                <a class="nav-link text-light" asp-area="" asp-controller="Ticket" asp-action="Index">
                                    <i class="bi bi-ticket-perforated"></i> Tickets
                                </a>
                            </li>

							<li class="nav-item">
								<a class="nav-link text-light" asp-area="" asp-controller="Watchlist" asp-action="Index">
									<i class="bi bi-bookmark-star"></i> Watchlist
								</a>
							</li>

							<li class="nav-item">
								<a class="nav-link text-light" asp-area="" asp-controller="Event" asp-action="Add">
									<i class="bi bi-ticket-perforated"></i> Add Event
								</a>
							</li>



                            @if (User.IsInRole("Admin"))
                        {
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle text-light fw-bold" href="#" id="manageDropdown"
                                   role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                    <i class="bi bi-tools"></i> Admin
                                </a>
                                <ul class="dropdown-menu dropdown-menu-dark border-0">
                                    <li>
                                        <a class="dropdown-item" asp-area="Admin" asp-controller="UserManagement" asp-action="Index">
                                            <i class="bi bi-building"></i> Manage Users
                                        </a>
                                    </li>
                                    <li>
                                        <a class="dropdown-item" asp-area="Admin" asp-controller="PlaceManagement" asp-action="Manage">
                                            <i class="bi bi-camera-reels"></i> Manage Places
                                        </a>
                                    </li>
                                    <li>
                                        <a class="dropdown-item" asp-area="Admin" asp-controller="EventManagement" asp-action="Manage">
                                            <i class="bi bi-ticket-detailed"></i> Manage Events
                                        </a>
                                    </li>
                                </ul>
                            </li>
                        }




						}

                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>

    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2025 - EventHubApp - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>


    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    @* <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script> *@
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.6/dist/js/bootstrap.bundle.min.js" integrity="sha384-j1CDi7MgGQ12Z7Qab0qlWQ/Qqz24Gc6BM0thvEMVjHnfYGF0rmFCozFSxQBxwHKO" crossorigin="anonymous"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)


</body>
</html>

EventHubApp/Views/Shared/_PlaceSearchAndFilterPartial.cshtml
@model IEnumerable<string>

<div class="row mb-4">
    <div class="col-md-6">
        <input type="text" id="searchBar" class="form-control shadow-sm" placeholder="Search for a place..." onkeyup="filterPlaces()">
    </div>
    <div class="col-md-6">
        <select id="cityFilter" class="form-select shadow-sm" onchange="filterPlaces()">
            <option value="">All Cities</option>
            @foreach (var city in Model)
            {
                <option value="@city">@city</option>
            }
        </select>
    </div>
</div>